const data = {
  products: [
    {
      _id: "1",
      name: "Navy Blue Suit",
      category: "Suit",
      image: "/images/product-1.jpg",
      price: 325,
      color: "Navy",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "2",
      name: "Grey Suit",
      category: "Suit",
      image: "/images/product-2.jpg",
      price: 225,
      color: "Grey",
      rating: 3.5,
      numReviews: 8,
      description: "High quality product",
    },
    {
      _id: "3",
      name: "White Button-Up",
      category: "Shirt",
      image: "/images/product-3.jpg",
      price: 60,
      color: "White",
      rating: 4.9,
      numReviews: 30,
      description: "High quality product",
    },
    {
      _id: "4",
      name: "Green Suit",
      category: "Suit",
      image: "/images/product-4.jpg",
      price: 299,
      color: "Green",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "5",
      name: "Salmon Suit",
      category: "Suit",
      image: "/images/product-5.jpg",
      price: 399,
      color: "Salmon",
      rating: 5,
      numReviews: 50,
      description: "High quality product",
    },
  ],
};
export default data;
